# Copyright (c) 2024, 2026, Oracle and/or its affiliates. All rights reserved.
# The Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl/
"""Skip rules and delete ordering."""

from __future__ import annotations

from .runtime_core import *

def is_oke_worker_instance(resource: ResourceRecord) -> bool:
    if resource.resource_type_normalized != "instance":
        return False
    searchable = json.dumps(
        {
            "display_name": resource.display_name,
            "freeform_tags": resource.raw.get("freeform_tags") or resource.raw.get("freeformTags"),
            "defined_tags": resource.raw.get("defined_tags") or resource.raw.get("definedTags"),
            "additional_details": resource.raw.get("additional_details")
            or resource.raw.get("additionalDetails"),
        },
        default=str,
    ).lower()
    display = resource.display_name.lower()
    if display.startswith("oke-"):
        return True
    oke_markers = ("oke", "containerengine", "kubernetes")
    worker_markers = ("nodepool", "node_pool", "node pool", "cluster_id", "clusterid")
    return any(marker in searchable for marker in oke_markers) and any(
        marker in searchable for marker in worker_markers
    )


def is_vcn_managed_dns_zone(resource: ResourceRecord) -> bool:
    if resource.resource_type_normalized != "zone":
        return False
    name = resource.display_name.lower()
    return name.endswith(".oraclevcn.com") or name.endswith(".in-addr.arpa")


def is_default_vcn_resource(resource: ResourceRecord) -> bool:
    if resource.resource_type_normalized not in DEFAULT_VCN_RESOURCE_TYPES:
        return False
    return resource.display_name.lower().startswith("default ")


def is_parent_managed_drg_resource(resource: ResourceRecord) -> bool:
    if resource.resource_type_normalized not in DRG_MANAGED_RESOURCE_TYPES:
        return False
    name = resource.display_name.lower()
    return name.startswith("default ") or name.startswith("autogenerated ")


def is_default_mysql_configuration(resource: ResourceRecord) -> bool:
    if resource.resource_type_normalized != "mysql_configuration":
        return False
    configuration_type = first_present(
        resource.raw.get("type"),
        resource.raw.get("configuration_type"),
        resource.raw.get("configurationType"),
    )
    return configuration_type.upper() == "DEFAULT"


def skip_reason_for_resource(resource: ResourceRecord) -> str | None:
    resource_type = resource.resource_type_normalized
    if resource_type == "public_ip":
        lifetime = first_present(
            resource.raw.get("lifetime"),
            resource.raw.get("public_ip_lifetime"),
            resource.raw.get("publicIpLifetime"),
        ).upper()
        if lifetime != "RESERVED":
            return "ephemeral or unverified public IP; only reserved public IPs are deleted"
    if resource_type in AUTO_MANAGED_NETWORK_RESOURCE_TYPES:
        return "auto-managed network artifact; deleted by the owning resource"
    if resource_type in PARENT_MANAGED_COMPUTE_RESOURCE_TYPES:
        return "parent-managed compute artifact; deleted by compute/container cleanup"
    if resource_type in VCN_MANAGED_DNS_RESOURCE_TYPES:
        return "VCN-managed DNS artifact; deleted by VCN cleanup"
    if is_vcn_managed_dns_zone(resource):
        return "VCN-managed DNS zone; deleted by VCN cleanup"
    if is_default_vcn_resource(resource):
        return "default VCN resource; deleted by VCN cleanup"
    if is_parent_managed_drg_resource(resource):
        return "default/autogenerated DRG resource; deleted by DRG cleanup"
    if is_default_mysql_configuration(resource):
        return "default MySQL configuration; OCI-managed and cannot be deleted"
    if resource_type in SKIP_RESOURCE_TYPES:
        return "resource type is intentionally not deleted"
    return None


def vcn_default_resource_ids(resources: list[ResourceRecord]) -> set[str]:
    default_ids: set[str] = set()
    for resource in resources:
        if resource.resource_type_normalized != "vcn":
            continue
        for key in (
            "default_dhcp_options_id",
            "defaultDhcpOptionsId",
            "default_route_table_id",
            "defaultRouteTableId",
            "default_security_list_id",
            "defaultSecurityListId",
        ):
            value = resource.raw.get(key)
            if value:
                default_ids.add(str(value))
    return default_ids


def volume_group_backup_member_ids(resources: list[ResourceRecord]) -> dict[str, str]:
    member_to_group: dict[str, str] = {}
    for resource in resources:
        if resource.resource_type_normalized != "volume_group_backup":
            continue
        for key in ("volume_backup_ids", "volumeBackupIds"):
            values = resource.raw.get(key)
            if not values:
                continue
            if isinstance(values, str):
                values = [values]
            for volume_backup_id in values:
                if volume_backup_id:
                    member_to_group[str(volume_backup_id)] = resource.identifier
    return member_to_group


def filter_and_order_resources(
    resources: list[ResourceRecord],
    include_terminal: bool,
    skip_oke_workers: bool,
    logger: logging.Logger,
) -> tuple[list[ResourceRecord], list[SkippedResource]]:
    to_delete: list[ResourceRecord] = []
    skipped: list[SkippedResource] = []
    seen_identifiers: set[str] = set()
    default_vcn_resource_ids = vcn_default_resource_ids(resources)
    volume_backup_to_group_backup = volume_group_backup_member_ids(resources)
    has_plannable_oke_cluster = any(
        resource.resource_type_normalized == "cluster"
        and (include_terminal or resource.lifecycle_state not in TERMINAL_LIFECYCLE_STATES)
        and not skip_reason_for_resource(resource)
        for resource in resources
    )
    has_plannable_db_system = any(
        resource.resource_type_normalized == "db_system"
        and (include_terminal or resource.lifecycle_state not in TERMINAL_LIFECYCLE_STATES)
        and not skip_reason_for_resource(resource)
        for resource in resources
    )

    for resource in resources:
        if resource.identifier in seen_identifiers:
            skipped.append(SkippedResource(resource, "duplicate identifier from search results"))
            continue
        seen_identifiers.add(resource.identifier)

        skip_reason = skip_reason_for_resource(resource)
        if skip_reason:
            skipped.append(SkippedResource(resource, skip_reason))
            continue
        if (
            resource.resource_type_normalized in DEFAULT_VCN_RESOURCE_TYPES
            and resource.identifier in default_vcn_resource_ids
        ):
            skipped.append(
                SkippedResource(
                    resource,
                    "default VCN resource; deleted by VCN cleanup",
                )
            )
            continue
        if not include_terminal and resource.lifecycle_state in TERMINAL_LIFECYCLE_STATES:
            skipped.append(SkippedResource(resource, f"terminal lifecycle state {resource.lifecycle_state}"))
            continue
        if resource.resource_type_normalized == "volume_backup":
            volume_group_backup_id = volume_backup_to_group_backup.get(resource.identifier)
            if volume_group_backup_id:
                skipped.append(
                    SkippedResource(
                        resource,
                        f"member of volume group backup {volume_group_backup_id}; volume group backup cleanup owns it",
                    )
                )
                continue
        if resource.resource_type_normalized == "node_pool" and has_plannable_oke_cluster:
            skipped.append(
                SkippedResource(
                    resource,
                    "OKE cluster is planned for deletion; cluster cleanup owns node pools",
                )
            )
            continue
        if resource.resource_type_normalized in PARENT_MANAGED_DATABASE_RESOURCE_TYPES and has_plannable_db_system:
            skipped.append(
                SkippedResource(
                    resource,
                    "Oracle DB system is planned for termination; DB system cleanup owns database child resources",
                )
            )
            continue
        if skip_oke_workers and is_oke_worker_instance(resource):
            skipped.append(
                SkippedResource(resource, "looks like an OKE worker instance; delete OKE node pool/cluster instead")
            )
            continue
        to_delete.append(resource)

    ordered = sorted(
        to_delete,
        key=lambda item: (
            item.priority,
            item.resource_type_normalized,
            item.display_name.lower(),
            item.identifier,
        ),
    )
    logger.info("Planned %s resources for deletion", len(ordered))
    logger.info("Skipped %s resources", len(skipped))
    return ordered, skipped
